name: Notificate Merged

on:
  push:
    branches: [dev]

jobs:
  build-test:
    name: Next Discord notification
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "Merged"
          description: "Merge 완료!! pull 받고 작업하세요!!"
          image: "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Mogazoa/user/152/1716473858977/123.png"
          color: 0x13ac13
          url: "https://github.com/Codeit-Part4-SFJs/WDYTA/pulls"
          username: GitHub Actions
          avatar_url: "https://sprint-fe-project.s3.ap-northeast-2.amazonaws.com/Mogazoa/user/152/1716473908144/124.png"
